//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Звук Алерта.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на бар Покупок.
        /// </summary>
        internal static string ColorBuy {
            get {
                return ResourceManager.GetString("ColorBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на бар Нейтральный.
        /// </summary>
        internal static string ColorN {
            get {
                return ResourceManager.GetString("ColorN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на бар Продаж.
        /// </summary>
        internal static string ColorSell {
            get {
                return ResourceManager.GetString("ColorSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интервал (слева и справа от бара).
        /// </summary>
        internal static string Diapazon {
            get {
                return ResourceManager.GetString("Diapazon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смещение Метки.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр -ОИ.
        /// </summary>
        internal static string FilterOIDw {
            get {
                return ResourceManager.GetString("FilterOIDw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр +ОИ.
        /// </summary>
        internal static string FilterOIUp {
            get {
                return ResourceManager.GetString("FilterOIUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вкл. Фильтр.
        /// </summary>
        internal static string FilterOn {
            get {
                return ResourceManager.GetString("FilterOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размер шрифта.
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимум.
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Минимум.
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вкл. Индикатор.
        /// </summary>
        internal static string OnOff {
            get {
                return ResourceManager.GetString("OnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык чисел.
        /// </summary>
        internal static string SetNum {
            get {
                return ResourceManager.GetString("SetNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зона коррекции.
        /// </summary>
        internal static string ShowBox {
            get {
                return ResourceManager.GetString("ShowBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Луч Фибо.
        /// </summary>
        internal static string ShowFibo33 {
            get {
                return ResourceManager.GetString("ShowFibo33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инфо.
        /// </summary>
        internal static string ShowInfo {
            get {
                return ResourceManager.GetString("ShowInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровни.
        /// </summary>
        internal static string ShowLVLs {
            get {
                return ResourceManager.GetString("ShowLVLs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Макс. Объём.
        /// </summary>
        internal static string ShowMaxV {
            get {
                return ResourceManager.GetString("ShowMaxV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показывать Язык чисел.
        /// </summary>
        internal static string ShowNum {
            get {
                return ResourceManager.GetString("ShowNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОИ.
        /// </summary>
        internal static string ShowOI {
            get {
                return ResourceManager.GetString("ShowOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень Pit.
        /// </summary>
        internal static string ShowPit {
            get {
                return ResourceManager.GetString("ShowPit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string ShowStatus {
            get {
                return ResourceManager.GetString("ShowStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Линия Волны.
        /// </summary>
        internal static string ShowTrend {
            get {
                return ResourceManager.GetString("ShowTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Делитель ОИ.
        /// </summary>
        internal static string SplitOI {
            get {
                return ResourceManager.GetString("SplitOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прозрачный фон Зоны коррекции.
        /// </summary>
        internal static string TransparentBG {
            get {
                return ResourceManager.GetString("TransparentBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Алерт.
        /// </summary>
        internal static string UseAlert {
            get {
                return ResourceManager.GetString("UseAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Алерт за 5 минут.
        /// </summary>
        internal static string UseAlert5 {
            get {
                return ResourceManager.GetString("UseAlert5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Растущий Объем.
        /// </summary>
        internal static string VolUp {
            get {
                return ResourceManager.GetString("VolUp", resourceCulture);
            }
        }
    }
}
